config/routes.rb
ActionController::Routing::Routes.draw do |map|
    
  map.resources :events, :collection => {:list => :get}
  
  map.resources :links, :collection => {:list => :get}

  map.resources :events

  map.resources :messages

  map.resources :categories

  map.resources :clubs

  map.resources :users
                
  map.resource :session

  map.resources :pages
  
  map.logout '/logout', :controller => 'sessions', :action => 'destroy'
  map.login  '/login',  :controller => 'sessions', :action => 'new'
  
  map.view_page ':name', :controller => 'viewer', :action => 'show'

  map.root :controller => "viewer", :action => 'show', :name => 'home'

  map.connect ':controller/:action/:id'
  map.connect ':controller/:action/:id.:format'
end

app/models/event.rb
class Event < ActiveRecord::Base
  has_and_belongs_to_many :clubs
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  # filters  
    before_filter :set_pagetitle, :except => [:list]
    before_filter :login_required, :except => [:list, :show]

  def set_pagetitle
    @pagetitle = 'Page Administration'
  end
  
  # GET /events
  # GET /events.xml
   
  def index
    @events = Event.find(:all)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @events }
    end
  end
  
  def list
    @pagetitle = 'Camping Schedule'
    @clubs = Club.find(:all, :order => 'state')
    @events = Event.find(:all)
    get_page_metadata  
  end

  # GET /events/1
  # GET /events/1.xml
  def show
    @event = Event.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @event }
    end
  end

  # GET /events/new
  # GET /events/new.xml
  def new
    @event = Event.new
    @clubs = Club.find(:all)
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.xml
  def create
    @event = Event.new(params[:event])

    respond_to do |format|
      if @event.save
        flash[:notice] = 'Event was successfully created.'
        format.html { redirect_to(@event) }
        format.xml  { render :xml => @event, :status => :created, :location => @event }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @event.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.xml
  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        flash[:notice] = 'Event was successfully updated.'
        format.html { redirect_to(@event) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @event.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.xml
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to(events_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= error_messages_for :event %>

<% form_for(@event) do |f| %>
  <p>
    <b>Host Club</b>
    <%= f.collection_select :club_ids, Club.find(:all, :order => 'state'), :id, :club_name, {}, :multiple => false %>
  <p>
  
  <p>
    <b>Location</b><br />
    <%= f.text_field :location %>
  </p>

  <p>
    <b>Name</b><br />
    <%= f.text_field :name %>
  </p>

  <p>
    <b>Location address</b><br />
    <%= f.text_field :location_address %>
  </p>

  <p>
    <b>Location city</b><br />
    <%= f.text_field :location_city %>
  </p>

  <p>
    <b>Location state</b><br />
    <%= f.text_field :location_state %>
  </p>

  <p>
    <b>Location zip</b><br />
    <%= f.text_field :location_zip %>
  </p>

  <p>
    <b>Reservation phone</b><br />
    <%= f.text_field :reservation_phone %>
  </p>

  <p>
    <b>Camping fee</b><br />
    <%= f.text_field :camping_fee %>
  </p>

  <p>
    <b>Event hosts</b><br />
    <%= f.text_field :event_hosts %>
  </p>

  <p>
    <b>Location gps</b><br />
    <%= f.text_field :location_gps %>
  </p>

  <p>
    <b>Notes</b><br />
    <%= f.text_area :notes %>
  </p>

  <p>
    <b>Start date</b><br />
    <%= f.date_select :start_date %>
  </p>

  <p>
    <b>End date</b><br />
    <%= f.date_select :end_date %>
  </p>

  <p>
    <%= f.submit "Update" %>
  </p>
<% end %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<h1>Listing events</h1>

<table>
  <tr>
    <th>Host Club</th>
    <th>Location</th>
    <th>Name</th>
    <th>Location address</th>
    <th>Location city</th>
    <th>Location state</th>
    <th>Location zip</th>
    <th>Reservation phone</th>
    <th>Camping fee</th>
    <th>Event hosts</th>
    <th>Location gps</th>
    <th>Notes</th>
    <th>Start date</th>
    <th>End date</th>
  </tr>

<% for event in @events %>
  <tr>
    <td><%=h event.host_club %></td>
    <td><%=h event.location %></td>
    <td><%=h event.name %></td>
    <td><%=h event.location_address %></td>
    <td><%=h event.location_city %></td>
    <td><%=h event.location_state %></td>
    <td><%=h event.location_zip %></td>
    <td><%=h event.reservation_phone %></td>
    <td><%=h event.camping_fee %></td>
    <td><%=h event.event_hosts %></td>
    <td><%=h event.location_gps %></td>
    <td><%=h event.notes %></td>
    <td><%=h event.start_date %></td>
    <td><%=h event.end_date %></td>
    <td><%= link_to 'Show', event %></td>
    <td><%= link_to 'Edit', edit_event_path(event) %></td>
    <td><%= link_to 'Destroy', event, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New event', new_event_path %>

app/views/events/list.html.erb
<h1>Camping Schedule</h1>
<% for club in @clubs %>
	<% unless club.events.empty? %>	
		<h2><%=h club.club_name %></h2>
<table>
  <tr>
    <th>Start date</th>
    <th>End date</th>
    <th>Location</th>
    <th>Location city</th>
    <th>Location state</th>
  </tr>
		<% for event in club.events %>
	    <tr>
        <td><%=h event.start_date %></td>
        <td><%=h event.end_date %></td>
        <td><%=h event.location %></td>
        <td><%=h event.location_city %></td>
        <td><%=h event.location_state %></td>
        <td><%= link_to 'Show', event %></td>
      </tr>
    <% end %>
  <% end %>
</table>  
<% end %>

app/views/events/new.html.erb
<h1>New event</h1>

<%= error_messages_for :event %>

<% form_for(@event) do |f| %>
  <p>
    <b>Host Club</b>
    <%= f.collection_select :club_ids, Club.find(:all, :order => 'state'), :id, :club_name, {}, :multiple => false %>
 <p>
  
  <p>
    <b>Location</b><br />
    <%= f.text_field :location %>
  </p>

  <p>
    <b>Name</b><br />
    <%= f.text_field :name %>
  </p>

  <p>
    <b>Location address</b><br />
    <%= f.text_field :location_address %>
  </p>

  <p>
    <b>Location city</b><br />
    <%= f.text_field :location_city %>
  </p>

  <p>
    <b>Location state</b><br />
    <%= f.text_field :location_state %>
  </p>

  <p>
    <b>Location zip</b><br />
    <%= f.text_field :location_zip %>
  </p>

  <p>
    <b>Reservation phone</b><br />
    <%= f.text_field :reservation_phone %>
  </p>

  <p>
    <b>Camping fee</b><br />
    <%= f.text_field :camping_fee %>
  </p>

  <p>
    <b>Event hosts</b><br />
    <%= f.text_field :event_hosts %>
  </p>

  <p>
    <b>Location gps</b><br />
    <%= f.text_field :location_gps %>
  </p>

  <p>
    <b>Notes</b><br />
    <%= f.text_area :notes %>
  </p>

  <p>
    <b>Start date</b><br />
    <%= f.date_select :start_date %>
  </p>

  <p>
    <b>End date</b><br />
    <%= f.date_select :end_date %>
  </p>

  <p>
    <%= f.submit "Create" %>
  </p>
<% end %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p>
  <b>Host Club:</b>
  <%=h @event.host_club %>
</p>

<p>
  <b>Location:</b>
  <%=h @event.location %>
</p>

<p>
  <b>Name:</b>
  <%=h @event.name %>
</p>

<p>
  <b>Location address:</b>
  <%=h @event.location_address %>
</p>

<p>
  <b>Location city:</b>
  <%=h @event.location_city %>
</p>

<p>
  <b>Location state:</b>
  <%=h @event.location_state %>
</p>

<p>
  <b>Location zip:</b>
  <%=h @event.location_zip %>
</p>

<p>
  <b>Reservation phone:</b>
  <%=h @event.reservation_phone %>
</p>

<p>
  <b>Camping fee:</b>
  <%=h @event.camping_fee %>
</p>

<p>
  <b>Event hosts:</b>
  <%=h @event.event_hosts %>
</p>

<p>
  <b>Location gps:</b>
  <%=h @event.location_gps %>
</p>

<p>
  <b>Notes:</b>
  <%=h @event.notes %>
</p>

<p>
  <b>Start date:</b>
  <%=h @event.start_date %>
</p>

<p>
  <b>End date:</b>
  <%=h @event.end_date %>
</p>

<% logged_in? %>
<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>